apiVersion: v1
kind: Service
metadata:
  name: headlamp-node-port
  namespace: headlamp
spec:
  type: NodePort
  selector:
    app: headlamp
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30808
    protocol: TCP
