apiVersion: apps/v1
kind: Deployment
metadata:
  name: govee-flask-server-exporter
  namespace: govee-flask-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: govee-flask-server-exporter
  template:
    metadata:
      labels:
        app: govee-flask-server-exporter
    spec:
      containers:
        - name: govee-flask-server-exporter
          image: nathannnli/mygovee:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 9101
          env:
            - name: GOVEE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: govee-secrets
                  key: api_key
            - name: GOVEE_DEVICE_ID
              valueFrom:
                secretKeyRef:
                  name: govee-secrets
                  key: device_id
            - name: GOVEE_DEVICE_SKU
              valueFrom:
                configMapKeyRef:
                  name: govee-config
                  key: GOVEE_DEVICE_SKU
---
apiVersion: v1
kind: Service
metadata:
  name: govee-flask-server-exporter
  namespace: govee-flask-server
spec:
  selector:
    app: govee-flask-server-exporter
  ports:
    - port: 9101
      targetPort: 9101
---
apiVersion: v1
kind: Service
metadata:
  name: govee-flask-server-exporter-nodeport
  namespace: govee-flask-server
spec:
  selector:
    app: govee-flask-server-exporter
  ports:
    - name: govee-flask-server-exporter-nodeport
      protocol: TCP
      port: 9101
      targetPort: 9101
      nodePort: 30102
  type: NodePort