additionalArguments:
  - "--entrypoints.web.address=0.0.0.0:80"
  - "--entrypoints.websecure.address=0.0.0.0:443"
  - "--providers.kubernetescrd"
  - "--providers.kubernetesingress"

# Disable IPv6 by not listening on [::]
# (Traefik will only listen on IPv4 this way)