additionalArguments:
  - "--providers.kubernetescrd"
  - "--providers.kubernetesingress"

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

service:
  ports:
    web:
      port: 80
      targetPort: 80
    websecure:
      port: 443
      targetPort: 443

ports:
  web:
    port: 80
  websecure:
    port: 443
