apiVersion: v1
kind: Secret
metadata:
  name: grafana-tls
  namespace: grafana
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    REPLACE_WITH_CERT_FOR_MYGRAFANA_INTERNAL
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    REPLACE_WITH_PRIVATE_KEY_FOR_MYGRAFANA_INTERNAL
    -----END PRIVATE KEY-----
