apiVersion: apps/v1
kind: Deployment
metadata:
  name: kasa-flask-server-exporter
  namespace: kasa-flask-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kasa-flask-server-exporter
  template:
    metadata:
      labels:
        app: kasa-flask-server-exporter
    spec:
      containers:
        - name: kasa-flask-server-exporter
          image: nathannnli/mykasa:latest
          ports:
            - containerPort: 9100
          envFrom:
            - configMapRef:
                name: kasa-config
---
apiVersion: v1
kind: Service
metadata:
  name: kasa-flask-server-exporter
  namespace: kasa-flask-server
spec:
  selector:
    app: kasa-flask-server-exporter
  ports:
    - port: 9100
      targetPort: 9100
