apiVersion: apps/v1
kind: Deployment
metadata:
  name: kasa-flask-server-exporter
  namespace: kasa-flask-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kasa-flask-server-exporter
  template:
    metadata:
      labels:
        app: kasa-flask-server-exporter
    spec:
      containers:
        - name: kasa-flask-server-exporter
          image: nathannnli/mykasa:v12
          imagePullPolicy: Always
          ports:
            - containerPort: 9101
          envFrom:
            - configMapRef:
                name: kasa-config
---
apiVersion: v1
kind: Service
metadata:
  name: kasa-flask-server-exporter
  namespace: kasa-flask-server
spec:
  selector:
    app: kasa-flask-server-exporter
  ports:
    - port: 9101
      targetPort: 9101
---
apiVersion: v1
kind: Service
metadata:
  name: kasa-flask-server-exporter-nodeport
  namespace: kasa-flask-server
spec:
  selector:
    app: kasa-flask-server-exporter
  ports:
    - name: kasa-flask-server-exporter-nodeport
      protocol: TCP
      port: 9101
      targetPort: 9101
      nodePort: 30101
  type: NodePort