apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-finance-channel-alert-bot
  namespace: discord-bots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-finance-channel-alert-bot
  template:
    metadata:
      labels:
        app: discord-finance-channel-alert-bot
    spec:
      containers:
      - name: discord-finance-channel-alert-bot
        image: nathannnli/mydiscordalertbot:v6
        env:
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: alert-bot-secrets
              key: bot_token
        - name: CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: alert-bot-secrets
              key: finance_channel_id
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: discord-finance-channel-alert-bot-node-port
  namespace: discord-bots
spec:
  type: NodePort
  selector:
    app: discord-finance-channel-alert-bot
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
