{
 "title": "basement",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "kWh by device",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "last_over_time(kasapower_watts[5m]) * 5 / 60 / 1000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "$ by device",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(device) (last_over_time(kasapower_watts[5m]) * 5 / 1000 / 60) * on() group_left electricity_price",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "cur electricity price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "electricity_price", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "sum energy cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(sum by(device) (last_over_time(kasapower_watts[5m]) * 5 / 1000 / 60) * on() group_left electricity_price)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "monitor ene",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "kasapower_watts{device=~\"LG45|alienware|odyssey-g9-49|odyssey-g9-57\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "monitor energy sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(kasapower_watts{device=~\"LGDualUp|alienware|odyssey-g9-57|LG45|odyssey-g9-49\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pc ene",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "kasapower_watts{device=~\"13k|14kf|14ks|285k|7950x|9950x|macmini|radiator\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "desktop energy sum",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(kasapower_watts{device=~\"13k|14kf|14ks|285k|7950x|9950x\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "govee temp F",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    { "expr": "govee_temperature_F", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "govee humidity %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    { "expr": "govee_humidity_percentage", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}